### ISSUE TITLE
Illegal config.json in the huggingface ecosystem!

### ISSUE THREAD

**Issue by michaelfeil** [MinishLab/model2vec#123]
Hey MinishLab! 

Thanks for building model2vec! I and some users of infinity (https://huggingface.co/minishlab/potion-base-8M/blob/main/config.json) have encountered issues inferencing / loading the model2vec models.

In particular, the config.json seems incorrect (missing architecture, only randomly named keys).
example: https://huggingface.co/minishlab/potion-base-8M/blob/main/config.json

This has lead that I spend a decent amount of my freetime, typing to fix it. I have not been able to write a simple and maintainable version to do this. (https://github.com/michaelfeil/infinity/issues/451)

This issue can be solved when this code is running.

```
# Not import .from_frozen, not using other libaries.
model = SentenceTransformer("minishlab/potion-base-8M") # unclear why the frozen models are not adapted to SentenceTransformer input.

embedding = model.encode(['dummy'])
```

Background: the forward pass and tokenization gets fully refactored. 

## TODOs:
- [ ] Write correct config.json after "training" step in model2vec
- [  ] Potentially implement a model class in hf - transformers to load the safetensors with the PCA layers etc.

**Comment by Pringled** [comment]
Hi @michaelfeil,

You can load our models either with our package, or with SentenceTransformers via the [StaticEmbedding module](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/models/StaticEmbedding.py). There are code examples in our readme [here](https://github.com/MinishLab/model2vec?tab=readme-ov-file#inference) that work out of the box. Via the SentenceTransformers integration you should be able to use our model in any existing workflows, e.g:

```python
from sentence_transformers import SentenceTransformer
from sentence_transformers.models import StaticEmbedding

# Initialize a StaticEmbedding module
static_embedding = StaticEmbedding.from_model2vec("minishlab/potion-base-8M")
model = SentenceTransformer(modules=[static_embedding])
embeddings = model.encode(["It's dangerous to go alone!", "It's a secret to everybody."])
```

Let me know if you have any further questions!

**Comment by michaelfeil** [comment]
Hi @Pringled,

This answer is not sufficient, why is `from sentence_transformers.models import StaticEmbedding` needed.

Most other models provide a `modules.json`.
https://huggingface.co/BAAI/bge-small-en-v1.5/blob/main/modules.json

Background:
```
def load_model(model_name_hf: str) -> SentenceTransformer
    # difficult magic
    is_reranker = config[architecture] contains "classification"
    is_classifer = config[architecture] contains "classification" and config.num_labels > 1
    is_embedder = not is_reranker  and not is_classifer 
    if config is real config is_embedder:
         return SentenceTransformer(model_name_hf)
    elif is_embedder  
       # guess this model string could be loaded via Model2Vec
       return SentenceTransformer(modules=[StaticEmbedding.from_model2vec(model_name_hf)])
   elif is_reranker:
       ...
```

Actual implementation

https://github.com/michaelfeil/infinity/blob/main/libs/infinity_emb/infinity_emb/transformer/embedder/sentence_transformer.py

**Comment by stephantul** [comment]
Hello @michaelfeil,

You don't need the additional import if you're up for saving potion as a SentenceTransformer. e.g.,

```python
from sentence_transformers import SentenceTransformer
from sentence_transformers.models import StaticEmbedding

# Initialize a StaticEmbedding module
static_embedding = StaticEmbedding.from_model2vec("minishlab/potion-base-8M")
model = SentenceTransformer(modules=[static_embedding])
model.save_pretrained("my_model")
```

You could then use `my_model` in your scripts. I feel like that's a decent workaround. 

Another workaround could be to load the metadata of the HF repo and see whether it is tagged with `model2vec`. If it is, then it's a model2vec model. No need to guess.

On to the other points: we never explicitly mention that we directly integrate with the Transformers library. For example: `model2vec` models have their own `library` tag in the huggingface hub, we never give examples of using it in Transformers, and the `use this Model` tab also doesn't mention Transformers. There's simply no reason to assume we do, and to create workarounds, we just don't offer it. It also wouldn't work out of the box even if you were to "fix" the `config.json`. The code simply isn't compatible with Transformers, and we never wanted to integrate directly with transformers. 

So I feel like your assumption that our config is "illegal" or contains "glutter" is unwarranted, and also uncharitable to us. We know what we're doing, we're just not doing what you assume we want to do. 

Finally, I want to also signal that you are being rude: I realize that there's probably a language barrier at play, English also isn't our first language, but this just reads like you assume we don't know what we're doing just because things don't work the way you want them to. Many times, people make choices for reasons unknown to you, choices that will look dumb at first glance. Instead of assuming they are dumb or have ill intent, you should try to see what they were trying to achieve, and revise your own assumptions.

Let me know if you have further questions.
