### ISSUE TITLE
Vocabulary option for models with sentencepiece tokenizer.

### ISSUE THREAD

**Issue by trpstra** [MinishLab/model2vec#135]
Hi,

Thanks a lot for this wonderful project! I tried to distill a model2vec model from `sentence-transformers/paraphrase-multilingual-mpnet-base-v2` by providing it with a vocabulary list for my domain, but got the following error message:

```
ValueError: You passed a vocabulary, but the model you are using does not use a WordPiece tokenizer. This is not supported yet.Feel free to open an issue if this is a blocker: https://github.com/MinishLab/model2vec/issues
```

So I took the liberty to open an issue, as you kindly suggested. ;-)

Ps. As a temporary work-around I had tried to distill the model using the tokenlearn recipe instead, but was surprised to find that the dataset for extracting features was hard-coded there (i.e. C4, which won't work for my language and domain). Changing the `tokenlearn` code to load any arbitrary `dataset` is an easy enough work-around for now, but I wanted to flag the issue here regardless, for awareness.

Cheers!

**Comment by stephantul** [comment]
Hello!

I don't think we'll be supporting Unigram tokenizers any time soon. This is because Unigram tokenizers sample from a probability distribution, and we don't really know how to correctly set the probabilities of the words you'll be adding, because we don't have access to word frequencies. Sorry to be the bearer of bad news.

If you have more information about your use-case, we might be able to come up with another solution.

I've added an issue to tokenlearn, see [here](https://github.com/MinishLab/tokenlearn/issues/10), we'll tackle it.

**Comment by trpstra** [comment]
I see, that makes sense. 

In that case, just distilling the model without providing an in-domain vocabulary and subsequently finetuning on a custom dataset with the tokenlearn method should still work, as that's not updating the tokenizer. Is that correct? 

(thanks for picking up the tokenlearn dataset issue!)

**Comment by stephantul** [comment]
Hey @trpstra,

sorry for the late reply! Yes, that should work, and should also work pretty well. It depends on your specific use-case of course, but in our case we've seen bigger gains from performing tokenlearn than adding a large number of tokens to the vocabulary. It depends a little bit of course. 

Please let us know what you run into in terms of results, super curious to hear about what worked and what didn't.

Stéphan

**Comment by stijn-ibis-ai** [comment]
Thanks a lot @stephantul !
I will try it out and report back. 
(Feel free to close this ticket if you like)
