### ISSUE TITLE
Potential tokenizer ordering issue

### ISSUE THREAD

**Issue by zechengz** [MinishLab/model2vec#85]
I think the tokenizers do not explicitly provide tokens sorted by frequency when we call `get_vocab()`
https://github.com/MinishLab/model2vec/blob/b4927e17494bd03e14ff51c1fa2aca059680df2d/model2vec/model.py#L45
In general the assigned IDs are not guaranteed to be sorted by frequency (though for some tokenizers the ID values may generally align with the frequency)
IMO this may influence the zipf re-weighting step right?

**Comment by stephantul** [comment]
Hey @zechengz,

Thanks for the issue. This is true, but it does seem to help performance in most cases. I also think the vocabularies are _de facto_ ordered by frequency because shorter subwords come before longer ones, and shorter strings are more frequent than longer ones. 

Do you have examples where applying the zipf transform doesn't work or tokenizers that are explicitly unordered?
